name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        When I run `zoomy create --start 2026-02-20T10:00:00 --duration 60`, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `zoomy create --start 2026-02-20T10:00:00 --duration 60`
        2. Observe error message
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: Meeting should be created successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error messages if any)
      placeholder: |
        Error: Authentication failed...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Zoomy version
      description: Run `zoomy --version` or `npm list zoomy`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      description: Run `node --version`
      placeholder: "v20.10.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 14.2, Ubuntu 22.04, Windows 11
      placeholder: "macOS 14.2"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs that might help
    validations:
      required: false
